# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HW_14' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HW_14
  pod 'RealmSwift'
  target 'HW_14Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HW_14UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
